### ISSUE TITLE
[EPIC] Gerenciamento de Certificados

### ISSUE THREAD

**Issue by JoaoVitorDMS** [ifpr-paranavai/portal-cdt#40]
### **Objetivo:**
Desenvolver uma funcionalidade completa para emissão, gerenciamento e distribuição de certificados acadêmicos para **MEMBROS**.

### **Descrição**:
COMO administrador QUERO PODER gerar certificados.

### **Histórias de Usuário:**
- [ ] COMO administrador QUERO gerar certificados acadêmicos em PDF PARA fornecer reconhecimento formal de conclusão do projeto.
- [ ] COMO administrador QUERO consultar o histórico de certificados emitidos PARA verificar e reemitir certificados se necessário.
- [ ] COMO usuário QUERO emitir meu certificado no portal para visualizar ou fazer download do certificado.
- [ ] COMO administrador QUERO PODER customizar as informações contidas no certificado.
- [ ] COMO administrador QUERO PODER ter como validar o certificado gerado no portal.
- [ ] COMO usuário QUERO que ao scanear o qrcode no certificado, ele já me leve para tela de validação do certificado.
