### ISSUE TITLE
[EPIC] Compressor de imagens

### ISSUE THREAD

**Issue by JoaoVitorDMS** [ifpr-paranavai/portal-cdt#52]
História de Usuário:
- Como Desenvolvedor quero que as imagens sejam comprimidas automaticamente ao serem carregadas para que eu possa garantir que o armazenamento do servidor seja otimizado
- Como um visitante quero que as imagens carreguem rapidamente para que eu possa navegar pelo site sem lentidão

Critérios de Aceitação:

- [ ] As imagens são comprimidas em um formato eficiente ao serem carregadas.
- [ ] O sistema deve manter uma qualidade visual satisfatória das imagens após a compressão.
- [ ] As imagens devem carregar em menos de 5 segundos em conexões padrão.
